
# This file is a template, and might need editing before it works on your project.

stages:
  - "docker-build"
  - "review"
# TESTED CODE TO PUSH DOCKER IMAGE TO PRIVATE DOCKER HUB
docker-build:
  image: docker:latest
  services:
    - name: docker:18.09.7-dind
  variables:
    DOCKER_HOST: tcp://localhost:2375
  stage: docker-build
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE":"$CI_PROJECT_TITLE-$CI_COMMIT_SHORT_SHA" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - merge_requests

# TESTED CODE FOR TRIGGERING HELM CHARTS FOR DEPLOYING
variables:
  KUBECONFIG: /etc/deploy/config
  BASE_URL: 192.168.99.100.nip.io
  NS: default

review:
  stage: review
  image: alpine/helm
  before_script:
    - mkdir -p /etc/deploy
    - touch ${KUBECONFIG}
  script:
    - DYNAMIC_ENVIRONMENT_URL=$CI_PROJECT_TITLE-$CI_COMMIT_SHORT_SHA
    - helm upgrade --install $DYNAMIC_ENVIRONMENT_URL  -n $NS --set image.tag="$CI_PROJECT_TITLE-$CI_COMMIT_SHORT_SHA" --set ingress.hosts[0].host=$DYNAMIC_ENVIRONMENT_URL.$BASE_URL  --set ingress.hosts[0].paths={"/"}  ./chart
  environment:
    name: dynamicenv/$CI_PROJECT_TITLE-$CI_COMMIT_SHORT_SHA
    url: http://$CI_PROJECT_TITLE-$CI_COMMIT_SHORT_SHA.$BASE_URL
    on_stop: stop_review
  only:
    - merge_requests

stop_review:
  stage: review
  image: alpine/helm
  before_script:
    - mkdir -p /etc/deploy
    - echo ${KUBECONF} | base64 -d > ${KUBECONFIG}
  script:
    - helm delete $CI_PROJECT_TITLE-$CI_COMMIT_SHORT_SHA -n $NS
  when: manual
  environment:
    name: dynamicenv/$CI_PROJECT_TITLE-$CI_COMMIT_SHORT_SHA
    action: stop
  only:
    - merge_requests